name: ht_sources_repository
description: Repository that manages news sources data.
repository: https://github.com/headlines-toolkit/ht-sources-repository
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  ht_shared:
    git:
      url: https://github.com/headlines-toolkit/ht-shared.git
  ht_sources_client:
    git:
      url: https://github.com/headlines-toolkit/ht-sources-client.git

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.15
  very_good_analysis: ^7.0.0
