name: ht_sources_repository
description: ...
repository: https://github.com/headlines-toolkit/ht-sources-firstore
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  flutter:
    sdk: flutter
  ht_sources_client:
    git:
      url: https://github.com/headlines-toolkit/ht-sources-client.git
  ht_sources_firestore:
    git:
      url: https://github.com/headlines-toolkit/ht-sources-firebase.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0
